services:
  app-{{BRANCH_NAME}}:
    build: .
    ports:
      - "{{PORT}}:3000"
      - "{{PORT_TTYD}}:{{PORT_TTYD}}"
    env_file:
      - .env
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    restart: unless-stopped
    container_name: hovel-app-{{BRANCH_NAME}}
    networks:
      - hovel-shared

networks:
  hovel-shared:
    external: true 